Repository IQSS/dataverse-client-javascript, pull requests merged in 2024-10, with the labels that each got.

#198 deploy_alpha.yml fix
  .github/workflows/deploy_alpha.yml
Labels: Size: 3, GREI Re-arch, SPA.Q3, FY25 Sprint 7, Original size: 3

#205 Add extra parameter to transform or not html to markdown
  docs/useCases.md
  src/datasets/domain/repositories/IDatasetsRepository.ts
  src/datasets/domain/useCases/GetDataset.ts
  src/datasets/domain/useCases/GetPrivateUrlDataset.ts
  src/datasets/infra/repositories/DatasetsRepository.ts
  src/datasets/infra/repositories/transformers/datasetTransformers.ts
  src/files/infra/repositories/transformers/fileTransformers.ts
  test/functional/datasets/GetDataset.test.ts
  test/integration/datasets/DatasetsRepository.test.ts
  test/unit/datasets/DatasetsRepository.test.ts
  test/unit/datasets/GetPrivateUrlDataset.test.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q4, FY25 Sprint 8, FY25 Sprint 9

#207 Use ':root', rather than alias 'root' for default root collection
  docs/useCases.md
  src/collections/domain/models/Collection.ts
  src/collections/domain/useCases/CreateCollection.ts
  src/collections/domain/useCases/GetCollection.ts
  src/collections/domain/useCases/GetCollectionFacets.ts
  src/collections/domain/useCases/GetCollectionUserPermissions.ts
  src/collections/infra/repositories/CollectionsRepository.ts
  src/datasets/domain/useCases/CreateDataset.ts
  src/metadataBlocks/domain/useCases/GetCollectionMetadataBlocks.ts
  test/functional/collections/GetCollectionFacets.test.ts
  test/functional/collections/GetCollectionUserPermissions.test.ts
  test/integration/collections/CollectionsRepository.test.ts
  test/integration/datasets/DatasetsRepository.test.ts
  test/testHelpers/collections/collectionHelper.ts
  test/unit/collections/CollectionsRepository.test.ts
  test/unit/datasets/CreateDataset.test.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q4, SPA.Q4.10, FY25 Sprint 9
