Repository IQSS/dataverse-client-javascript, pull requests merged in 2024-12, with the labels that each got.

#225 remove test step from pre-commit
  package.json
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q4.10, FY25 Sprint 11, FY25 Sprint 12

#226 Change file creation date and publication date in FileModel from date object to string type
  src/files/domain/models/FileModel.ts
  src/files/infra/repositories/transformers/fileTransformers.ts
  test/testHelpers/files/filesHelper.ts
Labels: Size: 3, SPA: File Page, GREI Re-arch, Original size: 3, SPA.Q4.10, FY25 Sprint 11, FY25 Sprint 12

#224 Add OIDC Bearer Token Auth mechanism based on the PoC design
  docs/useCases.md
  package-lock.json
  package.json
  src/core/infra/repositories/ApiConfig.ts
  src/core/infra/repositories/apiConfigBuilders.ts
  src/users/domain/dtos/UserDTO.ts
  src/users/domain/repositories/IUsersRepository.ts
  src/users/domain/useCases/RegisterUser.ts
  src/users/index.ts
  src/users/infra/repositories/UsersRepository.ts
  test/testHelpers/TestConstants.ts
  test/unit/auth/BearerTokenMechanism.test.ts
  test/unit/files/FilesRepository.test.ts
  test/unit/users/RegisterUser.test.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q4.4, FY25 Sprint 11, FY25 Sprint 12
