Repository IQSS/dataverse-client-javascript, pull requests merged in 2025-09, with the labels that each got.

#362 Get Available Dataset Metadata Export Formats Use Case
  docs/useCases.md
  src/info/domain/models/DatasetMetadataExportFormats.ts
  src/info/domain/repositories/IDataverseInfoRepository.ts
  src/info/domain/useCases/GetAvailableDatasetMetadataExportFormats.ts
  src/info/index.ts
  src/info/infra/repositories/DataverseInfoRepository.ts
  test/integration/info/DataverseInfoRepository.test.ts
  test/unit/info/DataverseInfoRepository.test.ts
Labels: GREI Re-arch, Size: 0.5, Original size: 0.5, SPA.Q3.2025.16

#355 Get Dataset Templates use case
  docs/useCases.md
  src/datasets/domain/models/Dataset.ts
  src/datasets/domain/models/DatasetTemplate.ts
  src/datasets/domain/repositories/IDatasetsRepository.ts
  src/datasets/domain/useCases/GetDatasetTemplates.ts
  src/datasets/index.ts
  src/datasets/infra/repositories/DatasetsRepository.ts
  src/datasets/infra/repositories/transformers/DatasetPayload.ts
  src/datasets/infra/repositories/transformers/DatasetTemplatePayload.ts
  src/datasets/infra/repositories/transformers/datasetTemplateTransformers.ts
  src/datasets/infra/repositories/transformers/datasetTransformers.ts
  src/licenses/domain/repositories/transformers/licenseTransformers.ts
  src/licenses/infra/repositories/LicensesRepository.ts
  test/functional/licenses/GetAvailableStandardLicenses.test.ts
  test/integration/datasets/DatasetsRepository.test.ts
  test/integration/licenses/LicensesRepository.test.ts
  test/testHelpers/datasets/datasetTemplatesHelper.ts
Labels: GREI Re-arch, FY25 Sprint 26, FY26 Sprint 1, Size: 0.5, SPA.Q3.2025.12, FY26 Sprint 2, FY26 Sprint 3, FY26 Sprint 4, FY26 Sprint 5

#372 Use Cases for Adding, Editing, and Deleting Dataset Types
  docs/useCases.md
  src/datasets/domain/models/DatasetType.ts
  src/datasets/domain/repositories/IDatasetsRepository.ts
  src/datasets/domain/useCases/AddDatasetType.ts
  src/datasets/domain/useCases/DeleteDatasetType.ts
  src/datasets/domain/useCases/GetDatasetAvailableDatasetType.ts
  src/datasets/domain/useCases/LinkDatasetTypeWithMetadataBlocks.ts
  src/datasets/domain/useCases/SetAvailableLicensesForDatasetType.ts
  src/datasets/index.ts
  src/datasets/infra/repositories/DatasetsRepository.ts
  test/functional/datasets/AddDatasetType.test.ts
  test/functional/datasets/DeleteDatasetType.test.ts
  test/functional/datasets/GetDatasetAvailableDatasetType.test.ts
  test/functional/datasets/LinkDatasetTypeWithMetadataBlocks.test.ts
  test/functional/datasets/SetAvailableLicensesForDatasetType.test.ts
  test/integration/datasets/DatasetsRepository.test.ts
  test/unit/datasets/DeleteDatasetType.test.ts
  test/unit/datasets/GetDatasetAvailableDatasetType.test.ts
  test/unit/datasets/LinkDatasetTypeWithMetadataBlocks.test.ts
  test/unit/datasets/SetAvailableLicensesForDatasetType.test.ts
Labels: GREI Re-arch

#373 Update CreateDataset use case to allow non-default dataset types
  docs/useCases.md
  src/datasets/domain/models/Dataset.ts
  src/datasets/domain/repositories/IDatasetsRepository.ts
  src/datasets/domain/useCases/CreateDataset.ts
  src/datasets/infra/repositories/DatasetsRepository.ts
  src/datasets/infra/repositories/transformers/DatasetPayload.ts
  src/datasets/infra/repositories/transformers/datasetTransformers.ts
  test/functional/datasets/CreateDataset.test.ts
  test/integration/datasets/DatasetsRepository.test.ts
  test/testHelpers/datasets/datasetHelper.ts
  test/unit/datasets/CreateDataset.test.ts
  test/unit/datasets/datasetTransformers.test.ts
Labels: GREI Re-arch, FY26 Sprint 6

#374 update getCollectionMetadataBlocks use case to support passing a dataset type
  docs/useCases.md
  src/metadataBlocks/domain/repositories/IMetadataBlocksRepository.ts
  src/metadataBlocks/domain/useCases/GetCollectionMetadataBlocks.ts
  src/metadataBlocks/infra/repositories/MetadataBlocksRepository.ts
Labels: GREI Re-arch, FY26 Sprint 6, FY26 Sprint 7
