Repository IQSS/dataverse-client-javascript, pull requests merged in 2025-01, with the labels that each got.

#234 Update file restriction fields and tabular information to the file preview
  src/datasets/domain/models/DatasetPreview.ts
  src/datasets/infra/repositories/transformers/DatasetPreviewPayload.ts
  src/datasets/infra/repositories/transformers/datasetPreviewsTransformers.ts
  src/files/domain/models/FilePreview.ts
  src/files/infra/repositories/transformers/FilePreviewPayload.ts
  src/files/infra/repositories/transformers/filePreviewTransformers.ts
  test/integration/collections/CollectionsRepository.test.ts
  test/testHelpers/datasets/datasetPreviewHelper.ts
  test/testHelpers/files/filePreviewHelper.ts
  test/testHelpers/files/filesHelper.ts
Labels: Size: 10, SPA: Collection Page, GREI Re-arch, Original size: 3, SPA.Q4.2, FY25 Sprint 14

#243 Get Dataset Extension: add Terms of Use
  src/datasets/domain/models/Dataset.ts
  src/datasets/infra/repositories/transformers/DatasetPayload.ts
  src/datasets/infra/repositories/transformers/datasetTransformers.ts
  test/testHelpers/datasets/datasetHelper.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, FY25 Sprint 15, SPA.Q1.3

#238 Typescript strict config
  src/collections/infra/repositories/CollectionsRepository.ts
  src/core/infra/repositories/ApiRepository.ts
  src/core/infra/repositories/apiConfigBuilders.ts
  src/datasets/domain/models/Dataset.ts
  src/datasets/domain/useCases/validators/DatasetResourceValidator.ts
  src/datasets/domain/useCases/validators/SingleMetadataFieldValidator.ts
  src/datasets/infra/repositories/transformers/datasetTransformers.ts
  src/files/infra/clients/DirectUploadClient.ts
  src/metadataBlocks/infra/repositories/transformers/metadataBlockTransformers.ts
  test/functional/collections/CreateCollection.test.ts
  test/functional/collections/GetCollectionFacets.test.ts
  test/functional/collections/GetCollectionItems.test.ts
  test/functional/collections/GetCollectionUserPermissions.test.ts
  test/functional/collections/UpdateCollection.test.ts
  test/functional/datasets/CreateDataset.test.ts
  test/functional/metadataBlocks/GetAllFacetableMetadataFields.test.ts
  test/functional/metadataBlocks/GetAllMetadataBlocks.test.ts
  test/functional/metadataBlocks/GetCollectionMetadataBlocks.test.ts
  test/integration/datasets/DatasetsRepository.test.ts
  test/unit/auth/AuthRepository.test.ts
  test/unit/datasets/DatasetResourceValidator.test.ts
  test/unit/files/FilesRepository.test.ts
  test/unit/files/GetFileDataTables.test.ts
  test/unit/info/GetDataverseVersion.test.ts
  test/unit/info/GetZipDownloadLimit.test.ts
  test/unit/metadataBlocks/GetMetadataBlockByName.test.ts
  test/unit/metadataBlocks/MetadataBlocksRepository.test.ts
  test/unit/users/UsersRepository.test.ts
  tsconfig.json
Labels: bug, Size: 3, GREI Re-arch, Original size: 3, SPA.Q4.10, SPA.Q1, FY25 Sprint 15
