Repository IQSS/dataverse-client-javascript, pull requests merged in 2025-02, with the labels that each got.

#235 Featured Items Use Cases
  docs/useCases.md
  src/collections/domain/dtos/CollectionFeaturedItemsDTO.ts
  src/collections/domain/models/CollectionFeaturedItem.ts
  src/collections/domain/repositories/ICollectionsRepository.ts
  src/collections/domain/useCases/DeleteCollectionFeaturedItems.ts
  src/collections/domain/useCases/GetCollectionFeaturedItems.ts
  src/collections/domain/useCases/UpdateCollectionFeaturedItems.ts
  src/collections/index.ts
  src/collections/infra/repositories/CollectionsRepository.ts
  src/collections/infra/repositories/transformers/CollectionFeaturedItemPayload.ts
  src/collections/infra/repositories/transformers/collectionFeaturedItemsTransformer.ts
  src/core/infra/repositories/ApiRepository.ts
  src/core/infra/repositories/apiConfigBuilders.ts
  test/functional/collections/DeleteCollectionFeaturedItems.test.ts
  test/functional/collections/GetCollectionFeaturedItems.test.ts
  test/functional/collections/UpdateCollectionFeaturedItems.test.ts
  test/integration/collections/CollectionsRepository.test.ts
  test/testHelpers/collections/collectionFeaturedItemsHelper.ts
  test/testHelpers/collections/collectionHelper.ts
  test/unit/collections/DeleteCollectionFeaturedItems.test.ts
  test/unit/collections/GetCollectionFeaturedItems.test.ts
  test/unit/collections/UpdateCollectionFeaturedItems.test.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q4.5, FY25 Sprint 14, SPA.Q1, FY25 Sprint 15, FY25 Sprint 16

#248 Get Dataset: add custom terms of use
  src/datasets/domain/models/Dataset.ts
  src/datasets/infra/repositories/transformers/DatasetPayload.ts
  src/datasets/infra/repositories/transformers/datasetTransformers.ts
  test/functional/datasets/GetDataset.test.ts
  test/functional/metadataBlocks/GetAllFacetableMetadataFields.test.ts
  test/functional/metadataBlocks/GetAllMetadataBlocks.test.ts
  test/integration/metadataBlocks/MetadataBlocksRepository.test.ts
  test/integration/metadataBlocks/MetadataFieldsInfoRepository.test.ts
  test/testHelpers/datasets/datasetHelper.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q1.3, FY25 Sprint 16

#250 Modify payload sent in Create/Update Collection - JS-Dataverse
  src/collections/domain/dtos/CollectionDTO.ts
  src/collections/infra/repositories/CollectionsRepository.ts
  test/integration/collections/CollectionsRepository.test.ts
  test/testHelpers/collections/collectionHelper.ts
Labels: bug, Size: 3, GREI Re-arch, Original size: 3, SPA.Q1, FY25 Sprint 16

#252 Get Dataset: refactor terms of use
  src/datasets/domain/models/Dataset.ts
  src/datasets/index.ts
  src/datasets/infra/repositories/transformers/datasetTransformers.ts
  test/functional/datasets/GetDataset.test.ts
  test/testHelpers/datasets/datasetHelper.ts
  test/unit/datasets/DatasetsRepository.test.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q1.3, FY25 Sprint 16

#253 245 delete file use case
  docs/useCases.md
  src/core/infra/repositories/ApiRepository.ts
  src/files/domain/repositories/IFilesRepository.ts
  src/files/domain/useCases/DeleteFile.ts
  src/files/index.ts
  src/files/infra/repositories/FilesRepository.ts
  test/functional/files/DeleteFile.test.ts
  test/integration/files/FilesRepository.test.ts
  test/unit/files/DeleteFile.test.ts
  test/unit/files/FilesRepository.test.ts
Labels: Size: 3, SPA: File Page, GREI Re-arch, Original size: 3, SPA.Q1.6, FY25 Sprint 16

#255 Implement Use Case for Deaccession Dataset
  docs/useCases.md
  src/datasets/domain/dtos/DatasetDeaccessionDTO.ts
  src/datasets/domain/repositories/IDatasetsRepository.ts
  src/datasets/domain/useCases/DeaccessionDataset.ts
  src/datasets/index.ts
  src/datasets/infra/repositories/DatasetsRepository.ts
  test/functional/datasets/DeaccessionDataset.test.ts
  test/integration/datasets/DatasetsRepository.test.ts
  test/testHelpers/datasets/datasetHelper.ts
  test/unit/datasets/DatasetsRepository.test.ts
  test/unit/datasets/DeaccessionDataset.test.ts
Labels: Size: 3, SPA: Dataset View Page, GREI Re-arch, Original size: 3, SPA.Q1.5, FY25 Sprint 16, FY25 Sprint 17

#265 Remove transform to markdown from Get Collection use case
  src/collections/infra/repositories/transformers/collectionTransformers.ts
  test/functional/collections/GetCollectionItems.test.ts
  test/integration/collections/CollectionsRepository.test.ts
  test/testHelpers/collections/collectionHelper.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q1, FY25 Sprint 17

#263 Delete Collection use case
  .github/workflows/copy_labels.yml
  docs/useCases.md
  src/collections/domain/models/Collection.ts
  src/collections/domain/repositories/ICollectionsRepository.ts
  src/collections/domain/useCases/DeleteCollection.ts
  src/collections/index.ts
  src/collections/infra/repositories/CollectionsRepository.ts
  src/collections/infra/repositories/transformers/CollectionPayload.ts
  src/collections/infra/repositories/transformers/collectionTransformers.ts
  test/functional/collections/DeleteCollection.test.ts
  test/integration/collections/CollectionsRepository.test.ts
  test/testHelpers/collections/collectionHelper.ts
  test/unit/auth/BearerTokenMechanism.test.ts
  test/unit/collections/CollectionsRepository.test.ts
  test/unit/collections/DeleteCollection.test.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q.1.7, FY25 Sprint 17

#267 Replace File use case
  docs/useCases.md
  src/files/domain/dtos/UploadedFileDTO.ts
  src/files/domain/repositories/IFilesRepository.ts
  src/files/domain/useCases/ReplaceFile.ts
  src/files/domain/useCases/UploadFile.ts
  src/files/index.ts
  src/files/infra/repositories/FilesRepository.ts
  test/integration/files/DirectUpload.test.ts
  test/testHelpers/files/filesHelper.ts
  test/unit/files/ReplaceFile.test.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q1.6, FY25 Sprint 17
