Repository IQSS/dataverse-client-javascript, pull requests merged in 2025-05, with the labels that each got.

#296 Get Application Terms of Use - Use Case
  docs/useCases.md
  src/info/domain/repositories/IDataverseInfoRepository.ts
  src/info/domain/useCases/GetApplicationTermsOfUse.ts
  src/info/index.ts
  src/info/infra/repositories/DataverseInfoRepository.ts
  test/integration/info/DataverseInfoRepository.test.ts
  test/testHelpers/info/infoHelper.ts
  test/unit/info/DataverseInfoRepository.test.ts
  test/unit/info/GetApplicationTermsOfUse.test.ts
Labels: Size: 3, Waiting, GREI Re-arch, Original size: 3, FY25 Sprint 22, SPA.Q2.7

#302 File: Use Case File Has Been Deleted
  docs/useCases.md
  src/files/domain/repositories/IFilesRepository.ts
  src/files/domain/useCases/IsFileDeleted.ts
  src/files/index.ts
  src/files/infra/repositories/FilesRepository.ts
  test/integration/files/FilesRepository.test.ts
  test/unit/files/IsFileDeleted.test.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, SPA.Q2, FY25 Sprint 23

#307 Avoid double encoding of search term
  src/collections/infra/repositories/CollectionsRepository.ts
  test/integration/collections/CollectionsRepository.test.ts
Labels: bug, Size: 3, GREI Re-arch, Original size: 3, SPA.Q2
