Repository IQSS/dataverse-client-javascript, pull requests merged in 2025-08, with the labels that each got.

#344 File: Use Case Get Available Dataset File Categories
  docs/useCases.md
  src/datasets/domain/repositories/IDatasetsRepository.ts
  src/datasets/domain/useCases/GetDatasetAvailableCategories.ts
  src/datasets/index.ts
  src/datasets/infra/repositories/DatasetsRepository.ts
  src/files/domain/useCases/UpdateFileCategories.ts
  src/files/domain/useCases/UpdateFileTabularTags.ts
  test/functional/datasets/GetDatasetAvailableCategories.test.ts
  test/integration/datasets/DatasetsRepository.test.ts
Labels: Size: 3, SPA: File Page, GREI Re-arch, Original size: 3, SPA.Q3.2025, FY26 Sprint 2, FY26 Sprint 3, FY26 Sprint 4

#351 Fix: avoid incorrect Filter Queries split causing value part to be truncated
  src/collections/infra/repositories/CollectionsRepository.ts
Labels: bug, GREI Re-arch, SPA.Q3.2025, Size: 0.5, Original size: 0.5

#335 Use Cases for Get Notifications and Delete Notifications
  docs/useCases.md
  src/index.ts
  src/notifications/domain/models/Notification.ts
  src/notifications/domain/repositories/INotificationsRepository.ts
  src/notifications/domain/useCases/DeleteNotification.ts
  src/notifications/domain/useCases/GetAllNotificationsByUser.ts
  src/notifications/domain/useCases/GetUnreadNotificationsCount.ts
  src/notifications/domain/useCases/MarkNotificationAsRead.ts
  src/notifications/index.ts
  src/notifications/infra/repositories/NotificationsRepository.ts
  src/notifications/infra/transformers/NotificationPayload.ts
  test/functional/notifications/DeleteNotification.test.ts
  test/functional/notifications/GetAllNotificationsByUser.test.ts
  test/integration/notifications/NotificationsRepository.test.ts
  test/unit/notifications/DeleteNotification.test.ts
  test/unit/notifications/GetAllNotificationsByUser.test.ts
  test/unit/notifications/GetUnreadCount.test.ts
  test/unit/notifications/MarkAsRead.test.ts
Labels: GREI Re-arch, Original size: 3, Original size: 10, FY26 Sprint 1, SPA.Q3.2025, FY26 Sprint 2, SPA.Q3.2025.6, FY26 Sprint 3, FY26 Sprint 4
