Repository IQSS/dataverse-client-javascript, pull requests merged in 2025-03, with the labels that each got.

#249 Implement updateFileMetadata use case
  docs/useCases.md
  src/files/domain/dtos/UpdateFileMetadataDTO.ts
  src/files/domain/repositories/IFilesRepository.ts
  src/files/domain/useCases/UpdateFileMetadata.ts
  src/files/index.ts
  src/files/infra/repositories/FilesRepository.ts
  test/functional/files/UpdateFileMetadata.test.ts
  test/functional/users/DeleteCurrentApiToken.test.ts
  test/integration/files/FilesRepository.test.ts
  test/testHelpers/files/filesHelper.ts
  test/unit/files/UpdateFileMetadata.test.ts
Labels: Size: 3, SPA: File Page, GREI Re-arch, Original size: 3, SPA.Q1.6, FY25 Sprint 16, FY25 Sprint 17, FY25 Sprint 18

#274 Implement Use Case for dataset download count
  docs/useCases.md
  src/datasets/domain/models/DatasetDownloadCount.ts
  src/datasets/domain/repositories/IDatasetsRepository.ts
  src/datasets/domain/useCases/GetDatasetDownloadCount.ts
  src/datasets/index.ts
  src/datasets/infra/repositories/DatasetsRepository.ts
  test/integration/datasets/DatasetsRepository.test.ts
  test/unit/datasets/DatasetsRepository.test.ts
  test/unit/datasets/GetDatasetDownloadCount.test.ts
Labels: Size: 3, GREI Re-arch, Original size: 3, FY25 Sprint 18, SPA.Q1.4, FY25 Sprint 19

#273 DatasetValidator allow empty fields for conditionally required fields.
  src/datasets/domain/models/Dataset.ts
  src/datasets/domain/repositories/IDatasetsRepository.ts
  src/datasets/domain/useCases/UpdateDataset.ts
  src/datasets/domain/useCases/validators/BaseMetadataFieldValidator.ts
  src/datasets/domain/useCases/validators/MetadataFieldValidator.ts
  src/datasets/domain/useCases/validators/SingleMetadataFieldValidator.ts
  src/datasets/infra/repositories/DatasetsRepository.ts
  src/datasets/infra/repositories/transformers/DatasetPayload.ts
  src/datasets/infra/repositories/transformers/datasetTransformers.ts
  test/integration/datasets/DatasetsRepository.test.ts
  test/testHelpers/datasets/datasetHelper.ts
  test/unit/datasets/DatasetResourceValidator.test.ts
  test/unit/datasets/UpdateDataset.test.ts
Labels: bug, Size: 3, GREI Re-arch, Original size: 3, SPA.Q1, SPA.Q1.6, FY25 Sprint 18

#277 fix tests due to dataverse api changes
  test/integration/collections/CollectionsRepository.test.ts
Labels: Size: 3, GREI Re-arch, Original size: 3

#278 Compare Dataset Versions use case extension: add includeDeaccessioned option
  docs/useCases.md
  src/datasets/domain/models/DatasetVersionDiff.ts
  src/datasets/domain/repositories/IDatasetsRepository.ts
  src/datasets/domain/useCases/GetDatasetVersionDiff.ts
  src/datasets/infra/repositories/DatasetsRepository.ts
  test/integration/datasets/DatasetsRepository.test.ts
  test/testHelpers/datasets/datasetVersionDiffHelper.ts
Labels: GREI Re-arch, SPA.Q1.5, FY25 Sprint 19, FY25 Sprint 20
